# syntax=docker/dockerfile:1.2
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Install basics
RUN apt update && apt install -y \
    wget git sudo build-essential \
    ca-certificates bzip2 curl python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Create a normal user
RUN useradd -m -s /bin/bash nat && \
    echo "nat ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER nat
WORKDIR /home/nat

# Install Miniforge
RUN wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh && \
    bash Miniforge3-Linux-x86_64.sh -b -p /home/nat/miniforge3 && \
    rm Miniforge3-Linux-x86_64.sh

ENV PATH="/home/nat/miniforge3/bin:$PATH"

# Create environment
RUN conda create -y -n surface_mesh python=3.10

# Install key packages (CPU-only)
RUN /home/nat/miniforge3/bin/mamba install -y -n surface_mesh \
    -c conda-forge mamba \
    numpy=1.24.4 scipy=1.8.1 pandas=2.1.2 ipython networkx \
    spyrmsd scikit-learn=1.3.2 biopython=1.79 loguru \
    rdkit openbabel tqdm mx::reduce && \
    /home/nat/miniforge3/bin/mamba clean -ya

# Install PyMesh2 first (precompiled wheel)
RUN /home/nat/miniforge3/bin/mamba run -n surface_mesh \
    pip install https://github.com/nuvolos-cloud/PyMesh/releases/download/v0.3.1/pymesh2-0.3.1-cp310-cp310-linux_x86_64.whl

# Activate environment by default
RUN echo "source /home/nat/miniforge3/bin/activate surface_mesh" >> ~/.bashrc