# syntax=docker/dockerfile:1.2
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Install basics
RUN apt update && apt install -y \
    wget git sudo build-essential \
    ca-certificates bzip2 curl \
    python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Create a normal user
RUN useradd -m -s /bin/bash nat && \
    echo "nat ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER nat
WORKDIR /home/nat

# Install Miniforge
RUN wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh && \
    bash Miniforge3-Linux-x86_64.sh -b -p /home/nat/miniforge3 && \
    rm Miniforge3-Linux-x86_64.sh

ENV PATH="/home/nat/miniforge3/bin:$PATH"

# Create ESMFold environment (CPU-only)
RUN /home/nat/miniforge3/bin/conda create -y -n esmfold python=3.7 setuptools=59.5.0 pip && \
    /home/nat/miniforge3/bin/mamba install -y -n esmfold \
        -c conda-forge \
        openmm=7.5.1 pdbfixer einops fairscale omegaconf hydra-core pandas pytest \
        -c bioconda \
        hmmer=3.3.2 hhsuite=3.3.0 kalign2 \
        -c pytorch \
        pytorch=1.12.* cpuonly && \
    /home/nat/miniforge3/bin/mamba clean -ya

# Install pip packages
RUN /home/nat/miniforge3/bin/mamba run -n esmfold \
    pip install biopython==1.79 \
                deepspeed==0.5.9 \
                dm-tree==0.1.6 \
                ml-collections==0.1.0 \
                numpy==1.21.2 \
                PyYAML==5.4.1 \
                requests==2.26.0 \
                scipy==1.7.1 \
                tqdm==4.62.2 \
                typing-extensions==3.10.0.2 \
                pytorch_lightning==1.5.10 \
                wandb==0.12.21 \
                git+https://github.com/NVIDIA/dllogger.git

# Activate environment by default
RUN echo "source /home/nat/miniforge3/bin/activate esmfold" >> ~/.bashrc

# Default working directory
WORKDIR /workspace