# syntax=docker/dockerfile:1.2
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Install basics
RUN apt update && apt install -y \
    wget git sudo build-essential \
    ca-certificates bzip2 curl python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Create a normal user
RUN useradd -m -s /bin/bash nat && \
    echo "nat ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER nat
WORKDIR /home/nat

# Install Miniforge
RUN wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh && \
    bash Miniforge3-Linux-x86_64.sh -b -p /home/nat/miniforge3 && \
    rm Miniforge3-Linux-x86_64.sh

ENV PATH="/home/nat/miniforge3/bin:$PATH"

# Create conda environment
RUN /home/nat/miniforge3/bin/conda create -y -n pose_scoring python=3.10 && \
    /home/nat/miniforge3/bin/mamba install -y -n pose_scoring \
        -c conda-forge \
        mamba numpy scipy pandas \
        scikit-learn biopython loguru && \
    /home/nat/miniforge3/bin/mamba clean -ya && \
    /home/nat/miniforge3/bin/mamba run -n pose_scoring pip install \
        torch==2.1.1+cpu torchvision \
    dimorphite_dl prefetch_generator posebusters \
    --index-url https://download.pytorch.org/whl/cpu \
    --extra-index-url https://pypi.org/simple

# Activate environment by default
RUN echo "source /home/nat/miniforge3/bin/activate pose_scoring" >> ~/.bashrc