FROM surfdock_base:latest

# Create conda environment
RUN /home/nat/miniforge3/bin/conda create -y -n docking_inference python=3.10 && \
    /home/nat/miniforge3/bin/mamba install -y -n docking_inference \
        -c conda-forge \
        mamba numpy==1.24.4 scipy==1.8.1 pandas==2.1.2 \
        scikit-learn==1.3.2 biopython==1.79 rdkit==2023.3.1 \
        wandb==0.16.1 loguru spyrmsd posebusters && \
    /home/nat/miniforge3/bin/mamba clean -ya && \
    /home/nat/miniforge3/bin/mamba run -n docking_inference pip install \
    torch==2.1.1+cpu torchvision \
    dimorphite_dl prefetch_generator posebusters \
    --index-url https://download.pytorch.org/whl/cpu \
    --extra-index-url https://pypi.org/simple

# Install PyG dependencies (CPU)
RUN /home/nat/miniforge3/bin/mamba run -n docking_inference \
    pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.2.0+cpu.html

# Activate by default
RUN echo "source /home/nat/miniforge3/bin/activate docking_inference" >> ~/.bashrc